### PR TITLE
[PlugingCore] - Shared library for Plugins [WIP].

### PR DESCRIPTION
**Pull request by ivandrofly**
This lib will contain all shared function/types Paragraph, Subtitle, TimeCodes...

### CODE REVIEW

**Comment by niksedk** [comment]
Hm, not really sure about this...
If you think it necessary with a shared lib we could just use a ref to SubtitleEdit.exe or libse.dll (I guess the last is only possible if we don't include libse in SubtitleEdit.exe).
What are your thought?

**Comment by ivandrofly** [comment]
Using SubtitleEdit.exe/libse.dll we will have to recompile all the plugins when once is a change occur in of these assemblies which will happen frequently...
Plugin core will contain share/common functionality  only and the chances changing will be low.

Plugin load for SE will be quite same, only few changes will be required.

**Comment by niksedk** [comment]
Still not too happy about this... each plug-in dll should have it's own dll or what? Seems to complicate things. (by the way - a few of the first plugins had references to SubtitleEdit.exe and it did not need recompiling).

**Comment by ivandrofly** [comment]
> each plug-in dll should have it's own dll or what?

No, all the plugin will share same dll, `PluginCore.dll` which will contain (Paragraph, TimeCode, Subtitle...).

The plugin load process will happen as following.

1. Load plugin1.dll (which have dependency on plugincore.dll)
     Load plugincore.dll (using AppDomain assembly resolve...).
2. Load plugin2.dll (since the plugincore.dll  is already loaded plugin2.dll will be loaded directly)...

**Pull request closed without merging**
